package edu.evacodekitchen.employees;

public enum Title {
	JUNIOR_SOFTWARE_DEVELOPER,
	SENIOR_SOFTWARE_DEVELOPER,
	ARCHITECT,
	SCRUM_MASTER,
	PRODUCT_MANAGER,
	PROJECT_MANAGER,
	PROGRAM_MANAGER,
	LINE_MANAGER
}
